[package]
name = "reamake"
version = "0.5.0"
edition = "2024"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[dependencies]
chrono = "0.4.41"
clap = "4.5.46"
progress_bar = "1.3.0"
yaml-rust2 = "0.10.3"
